web/router.ex
defmodule Jcb.Router do
  use Jcb.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Jcb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/transactions", TransactionController, except: [:delete]
    get "/users/:user_id/transactions", TransactionController, :mine
  end

  # Other scopes may use custom stacks.
  # scope "/api", Jcb do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Jcb.LayoutView do
  use Jcb.Web, :view

  def current_user conn do
    Plug.Conn.get_session conn, :current_user
  end

  defp user_token(conn) do
    if user = conn.assigns[:user] do
      Phoenix.Token.sign(conn, "user socket", user.username)
    end
  end

end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Hello Phoenix!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script>window.userToken = "<%= user_token(@conn) %>";</script>
  </head>

  <body>
    <div class="container" role="main">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <%= if user = current_user(@conn) do %>
            <li>
              <%= link "Give a JCB", to: transaction_path(@conn, :new) %>
            </li>
            <li>
              <%= link "Log out", to: session_path(@conn, :delete, user.id), method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link "Sign up", to: user_path(@conn, :new) %>
            </li>
            <li>
              <%= link "Log in", to: session_path(@conn, :new) %>
            </li>
          <% end %>
        </ul>
        <a href="/"><span class="logo"></span></a>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= @inner %>

    </div> <!-- /container -->
    <script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>